@fog_foundation @security
Feature: User-owned factotum authenticates standard 9P attaches
  Proofs establish a connection-local identity, not a portable bearer credential.
  The fixture uses the exact fog-auth-v1 documents and enrollment described in Authentication.md.

  @FOG_A01 @wire
  Scenario: A real local factotum signs the challenge without exporting its key
    Given an enrolled user and a running custom factotum with the matching signing key
    And a server-authenticated TLS connection to the configured fog host
    When the client reads an auth-fid challenge and validates its service and connection fields
    And the client signs those exact bytes using local monocypher sigcell RPC
    And the client writes the resulting proof document and attaches with that afid
    Then the attach resolves to the enrolled principal and its permitted root
    And no private key or factotum namespace is sent to the fog
    And every remote application frame decodes as standard 9P

  @FOG_A02 @property @wire
  Scenario: Authentication documents survive small messages and byte fragmentation
    Given an msize of 256 and a bounded canonical challenge and proof
    When their reads and writes are split at generated byte boundaries
    Then the reassembled challenge equals the exact bytes signed by factotum
    And intermediate proof writes do not authorize an attach
    And only the final valid sealed proof can complete authentication
    And no frame exceeds msize and no document exceeds its separate byte bound

  @FOG_A03
  Scenario Outline: A valid signature for another context cannot authenticate
    Given a cryptographically valid signature made by the enrolled user's key
    But the signed body belongs to <context>
    When that proof is submitted to the current authentication fid
    Then authentication fails and no root is attached

    Examples:
      | context                              |
      | a different user                     |
      | a different authentication domain    |
      | another configured server            |
      | another TLS server certificate       |
      | another connection session           |
      | another authentication fid           |
      | a preceding nonce on the same fid number |
      | a different export                   |
      | an old policy epoch                  |
      | the tpm9p-user-auth-v1 protocol       |

  @FOG_A04
  Scenario Outline: Enrollment and algorithm checks precede access
    Given a proof with <condition>
    When the server verifies it for the requested principal
    Then it returns the bounded auth-failed error
    And it grants no namespace or runtime access

    Examples:
      | condition                                      |
      | a valid signature from an unenrolled public key |
      | an unknown key ID                              |
      | another principal's enrolled key ID            |
      | a disabled key                                 |
      | a disabled principal                           |
      | an Ed25519 SHA-512 signature instead of BLAKE2b EdDSA |
      | a valid signature with modified body bytes     |

  @FOG_A05 @fuzz
  Scenario Outline: Malformed proofs cannot consume unbounded verification resources
    Given a pre-authentication session with finite byte and verification limits
    When it submits <input> and any incomplete attempt reaches its configured deadline
    Then the attempt fails without authorization or buffers beyond its limit
    And rejected framing is not passed as a valid prefix to cryptographic verification

    Examples:
      | input                                  |
      | duplicate attributes                   |
      | identical duplicate rows               |
      | an extra schema                        |
      | an unknown column                      |
      | noncanonical base64url                 |
      | invalid UTF-8                          |
      | an unterminated proof document         |
      | a document larger than 4096 bytes      |
      | bytes after the final empty line       |
      | a write gap or overlap                 |
      | a numeric field outside its range     |

  @FOG_A06 @property
  Scenario: Proof commit has one winner without forbidding matching attaches
    Given one valid unexpired proof and concurrent completion attempts on its afid
    When the attempts compete at the challenge-consumption barrier
    Then verification commits at most once and later proof writes fail
    When two unused root fids attach using that verified afid and matching user and export
    Then both obtain independently owned authorized namespace groups
    And changing the user or export on another attach is denied

  @FOG_A07 @wire
  Scenario: A lost proof reply is resolved through the known afid
    Given a proof that committed before its final Rwrite was lost
    When the client attaches with that afid on the same live connection
    Then the attach succeeds without replaying the proof write
    And no second authentication or key-use operation is required

  @FOG_A08 @property @wire
  Scenario Outline: Flushing verification respects the commit and reply barriers
    Given a proof verification and Tflush held at controlled barriers
    When <winner> wins the serialized race
    Then <result>
    And no response to the flushed request follows Rflush

    Examples:
      | winner              | result                                      |
      | flush before commit | the attempt is invalid and attach is denied |
      | verification commit | the authenticated afid remains attachable   |

  @FOG_A09
  Scenario Outline: Authentication cannot survive its session or deadline
    Given a live authentication attempt with an issued challenge
    When <event> occurs and its old proof is subsequently presented
    Then the old attempt cannot authorize an attach
    And its owned buffers and pending verification slots are reclaimed

    Examples:
      | event                        |
      | the monotonic deadline expires |
      | the afid is clunked           |
      | version negotiation resets the session |
      | the logical session is replaced |
      | the host restarts            |

  @FOG_A10
  Scenario: Client validation occurs before local signing
    Given a server-supplied challenge with a domain or certificate digest inconsistent with local trust
    When the client processes that challenge
    Then it rejects the challenge before sending a signing request to factotum
    And it does not acquire trust from the challenge's own fields

  @FOG_A11
  Scenario: Factotum refusal does not expose a fallback credential path
    Given a factotum whose vault is locked or whose key-use confirmation is denied
    When the client attempts fog authentication
    Then login fails without asking for or exporting the private seed
    And it does not retry using p9sk1, dp9ik, OAuth or plaintext

  @FOG_A12
  Scenario: Exhausted pre-auth limits preserve service progress
    Given one source has filled its configured outstanding-attempt and byte allowance
    When it requests another afid while another permitted source authenticates
    Then the first request is rejected without exceeding its reservation
    And the other source can complete within the fixture's available global allowance
    And slow logging cannot indefinitely block authentication cleanup
