namespace NinePSharp.Parser

open NinePSharp.Messages

type NinePMessage =
    | MsgTversion of Tversion
    | MsgRversion of Rversion
    | MsgTauth of Tauth
    | MsgRauth of Rauth
    | MsgTattach of Tattach
    | MsgRattach of Rattach
    | MsgRerror of Rerror
    | MsgRlerror of Rlerror
    | MsgTopen of Topen
    | MsgRopen of Ropen
    | MsgTcreate of Tcreate
    | MsgRcreate of Rcreate
    | MsgTread of Tread
    | MsgRread of Rread
    | MsgTwrite of Twrite
    | MsgRwrite of Rwrite
    | MsgTclunk of Tclunk
    | MsgRclunk of Rclunk
    | MsgTremove of Tremove
    | MsgRremove of Rremove
    | MsgTstat of Tstat
    | MsgRstat of Rstat
    | MsgTwstat of Twstat
    | MsgRwstat of Rwstat
    | MsgTwalk of Twalk
    | MsgRwalk of Rwalk
    | MsgTflush of Tflush
    | MsgRflush of Rflush
    | MsgTstatfs of Tstatfs
    | MsgRstatfs of Rstatfs
    | MsgTlopen of Tlopen
    | MsgRlopen of Rlopen
    | MsgTlcreate of Tlcreate
    | MsgRlcreate of Rlcreate
    | MsgTsymlink of Tsymlink
    | MsgRsymlink of Rsymlink
    | MsgTmknod of Tmknod
    | MsgRmknod of Rmknod
    | MsgTrename of Trename
    | MsgRrename of Rrename
    | MsgTreadlink of Treadlink
    | MsgRreadlink of Rreadlink
    | MsgTgetattr of Tgetattr
    | MsgRgetattr of Rgetattr
    | MsgTsetattr of Tsetattr
    | MsgRsetattr of Rsetattr
    | MsgTxattrwalk of Txattrwalk
    | MsgRxattrwalk of Rxattrwalk
    | MsgTxattrcreate of Txattrcreate
    | MsgRxattrcreate of Rxattrcreate
    | MsgTreaddir of Treaddir
    | MsgRreaddir of Rreaddir
    | MsgTfsync of Tfsync
    | MsgRfsync of Rfsync
    | MsgTlock of Tlock
    | MsgRlock of Rlock
    | MsgTgetlock of Tgetlock
    | MsgRgetlock of Rgetlock
    | MsgTlink of Tlink
    | MsgRlink of Rlink
    | MsgTmkdir of Tmkdir
    | MsgRmkdir of Rmkdir
    | MsgTrenameat of Trenameat
    | MsgRrenameat of Rrenameat
    | MsgTunlinkat of Tunlinkat
    | MsgRunlinkat of Runlinkat
