@fog_v1_profiles @aan @security
Feature: A fresh authenticated 9P bootstrap selects a live AAN session
  Bootstrap fids are disposable and never become the retained logical session's fids.

  @FOG_V1_AAN01 @wire
  Scenario Outline: Both owner kinds bootstrap without activating grains
    Given a fog-aan-v1 endpoint with grains and remote grain calls disabled
    When an enrolled <owner> authenticates to aname aan and allocates a session
    Then the bootstrap root and session challenge are available through standard 9P
    And the session is owned by the authenticated identity rather than its uname alone
    And no user or node private key is exported to the fog

    Examples:
      | owner |
      | user  |
      | node  |

  @FOG_V1_AAN02 @wire
  Scenario: Real factotum signs a validated session-specific intent
    Given a user bootstrap and a complete canonical fogaan-v1 challenge
    When the client validates it and asks its local factotum to produce a signed cell
    Then the server verifies the exact retained bytes under the session owner's enrolled key
    And the full challenge and proof fit their 2048 and 4096 byte limits
    And proof verification alone does not fence the existing carrier

  @FOG_V1_AAN03 @fuzz
  Scenario Outline: A valid signature in the wrong context cannot claim a session
    Given a pending AAN claim challenge
    When its supplied proof has <defect>
    Then claim verification fails without exposing retained bytes or evicting the owner

    Examples:
      | defect                                |
      | a fogauth-v1 body instead of fogaan-v1  |
      | a different session ID                |
      | a different server boot               |
      | a different carrier nonce             |
      | a different owner key                 |
      | a different logical export            |
      | a changed policy epoch                |
      | a stale consumed challenge            |

  @FOG_V1_AAN04 @property @wire
  Scenario: The switch reply is an exact parser handoff boundary
    Given one verified claim and its tunnel fid with all other bootstrap fids clunked
    And no pending bootstrap requests remain
    When the client writes switch and receives its complete Rwrite
    Then the recorder sees that Rwrite as the final bootstrap 9P frame
    And subsequent bytes are stock AAN records carrying logical 9P
    And buffered bytes are neither discarded nor interpreted by both parsers

  @FOG_V1_AAN05 @property
  Scenario: A lost switch reply cannot cause parser guessing
    Given a previously resumable logical session and a verified resume claim
    When the fixture cuts the switch request or reply at generated byte boundaries
    Then the client closes an ambiguous carrier instead of guessing its data phase
    And recovery uses fresh TLS, bootstrap authentication and a fresh claim
    And a retained generation advance never changes the logical session or owner

  @FOG_V1_AAN06 @property
  Scenario: Competing verified claims have one takeover winner
    Given two verified claims naming the same base generation
    When both attempt switch at competing barriers
    Then exactly one increments the generation and acquires the carrier
    And the loser cannot fence the winner or modify its ACK watermarks
    And generation overflow terminates instead of wrapping

  @FOG_V1_AAN07
  Scenario Outline: Switch requires quiescent bootstrap ownership
    Given a verified claim and a prepared tunnel fid
    When switch is attempted with <violation>
    Then the endpoint rejects or terminates that bootstrap without starting a logical request

    Examples:
      | violation                             |
      | another bootstrap fid still open      |
      | another request still pending         |
      | pipelined requests after switch       |
      | a tunnel naming a foreign claim fid   |
      | a claim whose deadline has expired    |

  @FOG_V1_AAN08
  Scenario: A stream is not resumable before its first authorized inner attach
    Given a newly switched session with incomplete inner authentication
    When its physical carrier fails before any authorized inner attach commits
    Then that session terminates within its handshake deadline
    And a new allocation cannot inherit its inner afids or pending requests

  @FOG_V1_AAN09
  Scenario: Certificate rotation requires a fresh logical session
    Given a suspended session pinned to a server TLS leaf certificate
    When a freshly trusted replacement certificate has a different leaf digest
    Then fog-aan-v1 refuses resumption of that old session
    And the client may create a separately authenticated new logical session
    And no old proof, fid or queued request migrates to it

  @FOG_V1_AAN10
  Scenario: Knowing a session ID does not make the node proof valid for a user
    Given a user session whose ID and challenge digest are known
    When a claimant submits a fogaannode-v1 hash without the enrolled node TLS profile
    Then it cannot authenticate or resume the user session
    And status never exposes a resume credential

  @FOG_V1_AAN11 @wire
  Scenario: Direct profile authentication cannot silently switch protocols
    Given a client connected to an explicitly direct 9P endpoint
    When it attempts the aan export or a switch command
    Then the endpoint rejects the unsupported profile without reinterpretation
    And no raw Orleans or plaintext fallback is opened
