<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NinePSharp.Namespaces.Orleans\NinePSharp.Namespaces.Orleans.csproj" />
    <ProjectReference Include="..\NinePSharp.Server.Abstractions\NinePSharp.Server.Abstractions.csproj" />
    <ProjectReference Include="..\NinePSharp.Server\NinePSharp.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NinePSharp.Namespaces.Orleans.Tests" />
  </ItemGroup>

</Project>
