import re, sys

source, revision = open(sys.argv[1]).read(), sys.argv[2]
names = ['yyexca', 'yyact', 'yypact', 'yypgo', 'yyr1', 'yyr2', 'yychk', 'yydef', 'yytok1', 'yytok2']
properties = {'yyexca': 'Exceptions', 'yyact': 'Actions', 'yypact': 'StateActions', 'yypgo': 'Gotos',
              'yyr1': 'RuleSymbols', 'yyr2': 'RuleLengths', 'yychk': 'Checks', 'yydef': 'Defaults',
              'yytok1': 'CharacterTokens', 'yytok2': 'PrivateTokens'}
defines = dict(re.findall(r'#define\s+(YYLAST|YYPRIVATE|YYFLAG|YYERRCODE|YYEOFCODE)\s+(-?\d+)', source))

def table(name):
    body = re.search(name + r'\[\]\s*=\s*\{(.*?)\};', source, re.S).group(1)
    return [int(v) for v in body.replace('\n', ' ').split(',') if v.strip()]

# RcParser indexes yyact without yacc's upper bound checks, which these tables never need.
last, flag = int(defines['YYLAST']), int(defines['YYFLAG'])
symbols = set(v for v in table('yytok1') + table('yytok2') if v)
pact, pgo = table('yypact'), table('yypgo')
assert all(p + s < last for p in pact if p > flag for s in symbols), 'a shift index reaches YYLAST'
assert all(g + state + 1 < last for g in set(pgo) for state in range(len(pact))), 'a goto index reaches YYLAST'
assert table('yychk')[table('yyact')[0]] not in symbols, 'yyact[0] is a shift, which RcParser reads for negative indexes'

print('// <auto-generated />')
print('// Generated by tools/rc-grammar/generate.sh from 9front sys/src/cmd/rc/syn.y at')
print(f'// {revision} with plan9port yacc. Do not edit.')
print('namespace NinePSharp.Fog.Rc;')
print()
print('internal static class RcTables')
print('{')
for name in ['YYLAST', 'YYPRIVATE', 'YYFLAG', 'YYERRCODE', 'YYEOFCODE']:
    const = {'YYLAST': 'Last', 'YYPRIVATE': 'Private', 'YYFLAG': 'Flag', 'YYERRCODE': 'ErrorCode', 'YYEOFCODE': 'EndOfFileCode'}[name]
    print(f'    internal const int {const} = {defines[name]};')
for name in names:
    body = re.search(name + r'\[\]\s*=\s*\{(.*?)\};', source, re.S).group(1)
    values = [v.strip() for v in body.replace('\n', ' ').split(',') if v.strip()]
    print()
    print(f'    internal static readonly short[] {properties[name]} =')
    print('    [')
    for i in range(0, len(values), 16):
        print('        ' + ', '.join(values[i:i + 16]) + ',')
    print('    ];')
print('}')
