<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NinePSharp\NinePSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Coyote" Version="1.7.11" />
  </ItemGroup>

</Project>
