<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../NinePSharp.Fog/NinePSharp.Fog.csproj" />
    <ProjectReference Include="../NinePSharp.Server/NinePSharp.Server.csproj" />
    <ProjectReference Include="../NinePSharp.Client/NinePSharp.Client.csproj" />
  </ItemGroup>
</Project>
