<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../NinePSharp.Fog/NinePSharp.Fog.csproj" />
    <ProjectReference Include="../NinePSharp.Server/NinePSharp.Server.csproj" />
    <ProjectReference Include="../NinePSharp.Client/NinePSharp.Client.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>NinePSharp.Fog.Server.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
