@libtab_jobs
Feature: Complete validated LibTab input is admitted exactly once per retained job
  LibTab parsing alone is not job validation. Uploads are staged and a successful
  start freezes one complete set of inputs before execution is admitted.

  @JOB_A01 @property @wire
  Scenario: Arbitrary 9P fragments assemble one document without executing a prefix
    Given a staging job and a valid UTF-8 LibTab specification
    When the client uploads it at contiguous offsets split at generated byte boundaries
    Then no runtime executes during the upload
    And splits inside a UTF-8 character or LibTab line do not corrupt the staged bytes
    When the client successfully clunks the upload and starts the job
    Then the service validates the complete original document and admits one run

  @JOB_A02
  Scenario: Start requires sealed uploads
    Given a staging job with an upload writer still open
    When the client writes start to ctl
    Then admission is rejected with upload-open
    And the job remains staging without execution
    When the writer seals a valid upload and the client starts again
    Then one run is admitted using the sealed bytes

  @JOB_A03
  Scenario: Terminal session loss discards an unsealed replacement
    Given a staging job with a sealed specification and input
    And a client has begun replacing the specification
    When that client's logical session terminates before sealing the replacement
    Then the incomplete replacement is discarded
    And the previous sealed specification and input remain unchanged
    And no run is admitted by the session termination

  @JOB_A04 @fuzz
  Scenario Outline: Invalid upload offsets cannot alter sealed or staged bytes
    Given a staging upload with a known accepted byte prefix and a configured byte limit
    When the client attempts <write>
    Then the write is rejected without changing the accepted prefix or sealed revision
    And the service does not allocate past the upload limit

    Examples:
      | write                              |
      | a write leaving an offset gap      |
      | a write overlapping accepted bytes |
      | a write whose end exceeds the limit |
      | a write whose offset arithmetic overflows |

  @JOB_A05
  Scenario: One writer owns staging while a document is being replaced
    Given a staging job with a writer holding spec open for replacement
    When another client attempts to open spec or input for writing
    Then the second writer is rejected with upload-busy
    And no interleaving of two upload streams changes the staged document

  @JOB_A06 @fuzz @security
  Scenario Outline: The job validator rejects unsafe or incomplete text
    Given a sealed specification containing <defect>
    When the client starts the job
    Then the service rejects validation without admitting execution
    And the job remains staging with a bounded diagnostic
    And the service does not accept a silently shortened or partially parsed document

    Examples:
      | defect                                      |
      | no schema entry                             |
      | an unsupported schema version               |
      | a missing provider_version                  |
      | an unregistered runtime and provider version pair |
      | an unknown column even though declared      |
      | a repeated schema column                    |
      | a repeated field within the job row         |
      | no job row                                  |
      | two identical job rows                      |
      | two different rows sharing the same job ID  |
      | a job ID different from the allocated ID    |
      | an invalid UTF-8 sequence                    |
      | an embedded NUL                             |
      | an unterminated final line                  |
      | an unterminated quoted value                |
      | an attribute name exceeding 31 bytes        |

  @JOB_A07 @property
  Scenario Outline: Required limits cannot become implicit unlimited values
    Given an otherwise valid job whose required memory_bytes value is <value>
    When the client starts the job
    Then validation rejects the limit without substituting an unlimited default
    And no worker is allocated to that job

    Examples:
      | value                        |
      | absent                       |
      | semantic nil                 |
      | empty text                   |
      | zero                         |
      | negative decimal             |
      | decimal with a plus sign     |
      | exponent notation            |
      | larger than the integer range |
      | larger than the principal quota |

  @JOB_A08 @property
  Scenario: Start freezes a coherent artifact and input revision
    Given a staging job referencing authorized source bytes and sealed input
    When validation and a concurrent replacement of that source are interleaved
    Then admission either pins a complete verified source revision or rejects validation
    And no run combines bytes from different source revisions
    When admission succeeds
    Then later path replacement and spec or input writes cannot change the frozen job

  @JOB_A09 @property
  Scenario: Concurrent starts admit only one run
    Given one retained staging job with valid sealed inputs
    And admission capacity is available while its worker is held at an execution barrier
    When two authorized clients start it concurrently
    Then both commands succeed and identify the same admitted job
    And exactly one transition out of staging occurs
    When the worker barrier is released and the fixture workload completes
    Then exactly one run has produced the expected result
    And repeating start returns the existing admission without another run

  @JOB_A10 @wire
  Scenario: A lost start reply is resolved by the retained job identity
    Given a start command that has admitted a job
    When its reply is lost before reaching the client
    And the authorized client reconnects and repeats start for that known job
    Then the existing admission is returned without a second run
    And the client need not allocate a replacement job to discover the outcome

  @JOB_A11
  Scenario: An admission rejection leaves the job correctable
    Given a staging job with valid sealed inputs but no available admission capacity
    When the client starts the job
    Then the service returns an admission-busy error without an unbounded queue
    And the job remains staging and editable
    When capacity becomes available and the client starts again
    Then one run is admitted

  @JOB_A12 @fuzz
  Scenario: A small-cell flood cannot bypass the document budget
    Given a spec upload whose individual lines fit the LibTab line limit
    When the client exceeds a configured total byte, row, or column limit
    Then the service rejects the upload or validation before unbounded parsing
    And no runtime is started from any accepted prefix
